WPVERITAS_URL: "https://wp-veritas-test.epfl.ch/api/v1/sites"
POD_NAME: "wp-httpd"
SERVICE_PORT: "3001"
NODE_TLS_REJECT_UNAUTHORIZED: "0"
PATH_REFRESH_FILE: "./data"
DEBUG: false
TEST_ENV: false
REST_URL_END: "wp-json/epfl/v1/menus/top?lang="
LABS_LINK_URL_FR: "https://www.epfl.ch/labs/fr/laboratoires/"
LABS_LINK_URL_EN: "https://www.epfl.ch/labs/en/laboratories/"
ASSOC_BREADCRUMB_EN: |
  https://www.epfl.ch/campus/en/campusenglish/
  https://www.epfl.ch/campus/associations/en/student-associations/
  https://www.epfl.ch/campus/associations/list/en/all-associations/
ASSOC_BREADCRUMB_FR: |
  https://www.epfl.ch/campus/fr/campus/
  https://www.epfl.ch/campus/associations/fr/associations-detudiants/
  https://www.epfl.ch/campus/associations/list/fr/toutes-les-associations/
MENU_BAR_LINKS_EN: |
  https://www.epfl.ch/about/en/
  https://www.epfl.ch/education/en/
  https://www.epfl.ch/research/en/
  https://www.epfl.ch/innovation/en/
  https://www.epfl.ch/schools/en/
  https://www.epfl.ch/campus/en/
  https://www.epfl.ch/labs/en/
MENU_BAR_LINKS_FR: |
  https://www.epfl.ch/about/fr/
  https://www.epfl.ch/education/fr/
  https://www.epfl.ch/research/fr/
  https://www.epfl.ch/innovation/fr/
  https://www.epfl.ch/schools/fr/
  https://www.epfl.ch/campus/fr/
  https://www.epfl.ch/labs/fr/
MENU_BAR_LINKS_DE: |
  https://www.epfl.ch/about/de/
  https://www.epfl.ch/education/de/
  https://www.epfl.ch/research/de/
  https://www.epfl.ch/innovation/de/
  https://www.epfl.ch/schools/de/
  https://www.epfl.ch/campus/de/
  https://www.epfl.ch/labs/en/
