WP_SERVICE_NAME: "localhost"
WP_SERVICE_PORT: 8000
SERVICE_PORT: "3001"
NODE_TLS_REJECT_UNAUTHORIZED: "0"
PATH_SITES_FILE: ""
NAMESPACE: "svc0041t-wordpress"
DEBUG: true
REQUEST_TIMEOUT: 30000
LABS_LINK_URL_FR: "https://wp-httpd/labs/fr/laboratoires/"
LABS_LINK_URL_EN: "https://wp-httpd/labs/en/laboratories/"
ROOT_LINK_URL: "https://wpn-test.epfl.ch/"
SITEMAP_LOCATION: "./data/sitemap.xml"
ASSOC_BREADCRUMB_EN: |
  https://wp-httpd/campus/en/campusenglish/
  https://wp-httpd/campus/associations/en/student-associations/
  https://wp-httpd/campus/associations/list/en/all-associations/
ASSOC_BREADCRUMB_FR: |
  https://wp-httpd/campus/fr/campus/
  https://wp-httpd/campus/associations/fr/associations-detudiants/
  https://wp-httpd/campus/associations/list/fr/toutes-les-associations/
MENU_BAR_LINKS_EN: |
  https://wpn-test.epfl.ch/about/en/
  https://wpn-test.epfl.ch/education/en/
  https://wpn-test.epfl.ch/research/en/
  https://wpn-test.epfl.ch/innovation/en/
  https://wpn-test.epfl.ch/schools/en/
  https://wpn-test.epfl.ch/campus/en/
  https://wpn-test.epfl.ch/labs/en/
MENU_BAR_LINKS_FR: |
  https://wpn-test.epfl.ch/about/fr/
  https://wpn-test.epfl.ch/education/fr/
  https://wpn-test.epfl.ch/research/fr/
  https://wpn-test.epfl.ch/innovation/fr/
  https://wpn-test.epfl.ch/schools/fr/
  https://wpn-test.epfl.ch/campus/fr/
  https://wpn-test.epfl.ch/labs/fr/
MENU_BAR_LINKS_DE: |
  https://wpn-test.epfl.ch/about/de/
  https://wpn-test.epfl.ch/education/de/
  https://wpn-test.epfl.ch/research/de/
  https://wpn-test.epfl.ch/innovation/de/
  https://wpn-test.epfl.ch/schools/de/
  https://wpn-test.epfl.ch/campus/de/
  https://wpn-test.epfl.ch/labs/en/
