WP_SERVICE_NAME: "172.24.0.6"
WP_SERVICE_PORT: 8080
SERVICE_PORT: "3001"
NODE_TLS_REJECT_UNAUTHORIZED: "0"
PATH_REFRESH_FILE: "./data"
PATH_SITES_FILE: "./sites.yaml"
NAMESPACE: "svc0041t-wordpress"
DEBUG: true
LABS_LINK_URL_FR: "https://wp-httpd/labs/fr/laboratoires/"
LABS_LINK_URL_EN: "https://wp-httpd/labs/en/laboratories/"
ASSOC_BREADCRUMB_EN: |
  https://wp-httpd/campus/en/campusenglish/
  https://wp-httpd/campus/associations/en/student-associations/
  https://wp-httpd/campus/associations/list/en/all-associations/
ASSOC_BREADCRUMB_FR: |
  https://wp-httpd/campus/fr/campus/
  https://wp-httpd/campus/associations/fr/associations-detudiants/
  https://wp-httpd/campus/associations/list/fr/toutes-les-associations/
MENU_BAR_LINKS_EN: |
  https://wp-httpd/about/en/
  https://wp-httpd/education/en/
  https://wp-httpd/research/en/
  https://wp-httpd/innovation/en/
  https://wp-httpd/schools/en/
  https://wp-httpd/campus/en/
  https://wp-httpd/labs/en/
MENU_BAR_LINKS_FR: |
  https://wp-httpd/about/fr/
  https://wp-httpd/education/fr/
  https://wp-httpd/research/fr/
  https://wp-httpd/innovation/fr/
  https://wp-httpd/schools/fr/
  https://wp-httpd/campus/fr/
  https://wp-httpd/labs/fr/
MENU_BAR_LINKS_DE: |
  https://wp-httpd/about/de/
  https://wp-httpd/education/de/
  https://wp-httpd/research/de/
  https://wp-httpd/innovation/de/
  https://wp-httpd/schools/de/
  https://wp-httpd/campus/de/
  https://wp-httpd/labs/en/
